name: Build and test

on:
  schedule:
    - cron: '27 10 * * *'
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-test:
    uses: davidstone/cmake_strict_defaults/.github/workflows/build-and-test.yml@main
    with:
      event_name: ${{github.event_name}}