name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    uses: davidstone/cmake_strict_defaults/.github/workflows/build-and-test.yml@main
