name: Build and test

on:
  schedule:
    - cron: '27 5 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: davidstone/cmake_strict_defaults@main
